# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 12:08
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup')], default='pickup', max_length=254, verbose_name='Delivery method'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service_point_full',
            field=models.CharField(blank=True, max_length=254, verbose_name='Service point for selected method'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service_point_id_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Delivery service point id and name'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_shipment_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shipment number for delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Set the relevance of products with the weight.', null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option3',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option4',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.IntegerField(choices=[(1, 'Size'), (2, 'Colour'), (3, 'Property'), (4, 'Order')], verbose_name='Type'),
        ),
    ]
