# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
        ('shop', '0015_auto_20160112_1432'),
    ]

    operations = [
    ]
